# This is an updated config for using I3D on ActivtyNet, resulting in slightly
# better performance. To reproduce the setting in our paper, set
# max_seq_len: 160,
# n_mha_win_size: [11, 11, 11, 11, -1, -1],

dataset_name: kinetics
model_name: TriDet
train_split: ['all']
#train_split: ['train', 'val']
val_split: ['test']
dataset: {
  json_file: /mnt/hdd0/kinetics-dataset/k400/annotations/kinetics-400.json,
  definition_file: /mnt/ssd0/VAD/definition/kinetics_definition.json,
  feat_folder: /mnt/hdd1/kinetics/k400/i3d_features_T16S8,
  file_prefix: "",
  file_ext: .npy,
  num_classes: 1,
  input_dim: 2304,
  feat_stride: 8,
  num_frames: 16,
  default_fps: 25,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  # upsample the features to a fixed length of 384
#  max_seq_len: 384, # 384
  max_seq_len: 2304, # 384
  force_upsampling: True,
  use_definition: False,
}

#model: {
#  fpn_type: identity,
#  max_buffer_len_factor: 1.0,
#  backbone_arch: [ 2, 2, 5 ],
#  n_sgp_win_size: 3,
#  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
#  embd_dim: 1024,
#  sgp_mlp_dim: 1024,
#  fpn_dim: 1024,
#  head_dim: 1024,
#  head_kernel_size: 5,
#  boudary_kernel_size: 1,
#  use_abs_pe: True,
#  num_bins: 14,
#  iou_weight_power: 1,
#  input_noise: 0.2,
#  use_trident_head: True,
#  k: 1.2,
#  init_conv_vars: 0.1,
#}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  backbone_arch: [ 2, 2, 5 ],
  n_sgp_win_size: 1,
  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
  num_bins: 16,
  k: 5,
  iou_weight_power: 0.2,
  use_trident_head: True,
  sgp_mlp_dim: 768,
  input_noise: 0.0005
}
opt: {
  learning_rate: 1.0e-3, # 1.0e-3
  eta_min: 0.0005,
  epochs: 5, # 10
  warmup: True,
  warmup_epochs: 5, # 5
  weight_decay: 0.05, # 0.05
}
loader: {
  batch_size: 32, # 256
  num_workers: 24, # 24
}
train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 0.5,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.95,
  pre_nms_topk: 2000,
  max_seg_num: 250,
  min_score: 0.001,
  multiclass_nms: True,
  nms_sigma: 0.75,
}
output_folder: ./ckpt/